force-app/main/default/objects/Lead/fields/Achievement_Points__c.field-meta.xml
<CustomField>
    <fullName>Achievement_Points__c</fullName>
    <label>Achievement Points</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Character_Render__c.field-meta.xml
<CustomField>
    <fullName>Character_Render__c</fullName>
    <label>Character Render</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Class of the player</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Faction__c.field-meta.xml
<CustomField>
    <fullName>Faction__c</fullName>
    <label>Faction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Item_Level__c.field-meta.xml
<CustomField>
    <fullName>Item_Level__c</fullName>
    <label>Item Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Main_Spec__c.field-meta.xml
<CustomField>
    <fullName>Main_Spec__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select the main spec of the lead</description>
    <inlineHelpText>Select the main spec of the lead</inlineHelpText>
    <label>Main Spec</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Specialization__c.Class__c</field>
            <operation>equals</operation>
            <valueField>$Source.Class__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Leads.cls
public with sharing class Leads {

    private String realmSlug;
    private String characterName;
    private String locale;
    private String namespaceProfile;
    
    public Leads() { }

    public Leads(String realmSlug, String characterName, String locale, String namespaceProfile) {

        this.realmSlug = realmSlug;
        this.characterName = characterName;
        this.locale = locale;
        this.namespaceProfile = namespaceProfile;

        String characterProfile = WoWProfileAPI.fetchCharacterProfileSummary(realmSlug, characterName, namespaceProfile);
        String characterEquipment = WoWProfileAPI.fetchCharacterEquipmentSummary(realmSlug, characterName, namespaceProfile, locale);
        String characterMedia = WoWProfileAPI.fetchCharacterMediaSummary(realmSlug, characterName, namespaceProfile, locale);

        CharacterProfileSummaryObject characterProfileObject = (CharacterProfileSummaryObject) JSON.deserialize(characterProfile.replaceAll('_links', 'links'), CharacterProfileSummaryObject.class);
        CharacterEquipmentSummaryObject characterEquipmentObject = (CharacterEquipmentSummaryObject) JSON.deserialize(characterEquipment.replaceAll('set', 'set_bonus').replaceAll('_links', 'links').replaceAll('links', 'links_extra'), CharacterEquipmentSummaryObject.class);
        CharacterMediaSummaryObject characterMediaObject = (CharacterMediaSummaryObject) JSON.deserialize(characterMedia.replaceAll('_links', 'links'), CharacterMediaSummaryObject.class);

        List<Class__c> classId = [SELECT Id FROM Class__c WHERE Name =: characterProfileObject.character_class.name.en_US];
        List<Specialization__c> classSpecId = [SELECT Id FROM Specialization__c WHERE Class__c =: classId AND Name =: characterProfileObject.active_spec.name.en_US];

        Lead lead = new Lead(
            LastName=characterName,
            Company='WoW API',
            Realm__c=characterProfileObject.realm.name.en_US,
            Faction__c=characterProfileObject.faction.name.en_US,
            Class__c=classId.get(0).Id,
            Main_Spec__c=classSpecId.get(0).Id,
            Level__c=characterProfileObject.level,
            Item_Level__c=characterProfileObject.equipped_item_level,
            Race__c=characterProfileObject.race.name.en_US,
            Achievement_Points__c=characterProfileObject.achievement_points,
            Character_Render__c=characterMediaObject.assets[2].value
        );

        try{
            upsert lead;
        } catch (DmlException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }

    }

}