force-app/main/default/objects/Lead/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Class of the player</description>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Faction__c.field-meta.xml
<CustomField>
    <fullName>Faction__c</fullName>
    <label>Faction</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Item_Level__c.field-meta.xml
<CustomField>
    <fullName>Item_Level__c</fullName>
    <label>Item Level</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Main_Spec__c.field-meta.xml
<CustomField>
    <fullName>Main_Spec__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Select the main spec of the lead</description>
    <inlineHelpText>Select the main spec of the lead</inlineHelpText>
    <label>Main Spec</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Specialization__c.Class__c</field>
            <operation>equals</operation>
            <valueField>$Source.Class__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Specialization__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WoWCharacter.cls
public with sharing class WoWCharacter {

    public static void createCharacterLead(String realmSlug, String characterName) {

        String characterProfile = WoWProfileAPI.fetchCharacterProfileSummary(realmSlug, characterName);
        CharacterProfileSummaryObject characterProfileObject = (CharacterProfileSummaryObject) JSON.deserialize(characterProfile.replaceAll('_links', 'links'), CharacterProfileSummaryObject.class);
        
        Id classId = [SELECT Id FROM Class__c WHERE Name =: characterProfileObject.character_class.name.en_US LIMIT 1].Id;
        Id specId = [SELECT Id FROM Specialization__c WHERE Class__c =: classId AND Name =: characterProfileObject.active_spec.name.en_US LIMIT 1].Id;
        Id realmId = [SELECT Id FROM Realm__c WHERE Name =: characterProfileObject.realm.name.en_US LIMIT 1].Id;

        Lead characterLead = new Lead(
            LastName=characterName,
            Company='WoW API',
            Realm__c=realmId,
            Faction__c=characterProfileObject.faction.name.en_US,
            Class__c=classId,
            Main_Spec__c=SpecId,
            Level__c=characterProfileObject.level,
            Item_Level__c=characterProfileObject.equipped_item_level,
            Race__c=characterProfileObject.race.name.en_US
        );

        try{
            if(Schema.SObjectType.Lead.isCreateable()
            && Schema.SObjectType.Lead.isUpdateable()){
                upsert characterLead;
            }
        } catch (DmlException e) {
            System.debug('The following exception has occurred when trying to upsert a Character Lead: ' + e.getMessage());
        }
    }

    public static void createCharacterModel(String realmSlug, String characterName) {

        String characterMedia = WoWProfileAPI.fetchCharacterMediaSummary(realmSlug, characterName);
        String characterEquipment = WoWProfileAPI.fetchCharacterEquipmentSummary(realmSlug, characterName);
        

        CharacterMediaSummaryObject characterMediaObject = (CharacterMediaSummaryObject) JSON.deserialize(characterMedia.replaceAll('_links', 'links'), CharacterMediaSummaryObject.class);
        CharacterEquipmentSummaryObject characterEquipmentObject = (CharacterEquipmentSummaryObject) JSON.deserialize(characterEquipment.replaceAll('set', 'set_bonus').replaceAll('_links', 'links').replaceAll('links', 'links_extra'), CharacterEquipmentSummaryObject.class);
        // ItemMediaObject media = (ItemMediaObject)JSON.deserialize(res.getBody().replaceAll('_links', 'links'), ItemMediaObject.class);

        // Id leadId = [SELECT Id FROM Lead WHERE LastName =: characterEquipmentObject.character.name AND Realm__c =: characterEquipmentObject.character.realm.name].Id;

    }

}